### PR TITLE
Upgrade Ruby to 2.4

### PR DESCRIPTION
**Pull request by Drenmi**
Newest and best. 💎 

---

**Before submitting, check that:**

 - [ ] You have added (passing) tests for your code.
 - [X] You have written good* commit messages.
 - [X] You have squashed relevant commits together.
 - [X] You have ensured that RuboCop is passing.
 - [X] Your PR relates to one subject.
 - [ ] If it relates to a GitHub issue, you have prefixed the title with `[Fix #n]`.

---

*If you do not know what makes a good commit message, or why it
is important, please refer to these resources: [1][1], [2][2], [3][3].

[1]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[2]: http://chris.beams.io/posts/git-commit/
[3]: https://github.com/blog/1943-how-to-write-the-perfect-pull-request

### CODE REVIEW

**Comment by hanmd82** [comment]
LGTM :+1:

**Comment by tgxworld** [comment]
https://www.ruby-lang.org/en/news/2017/03/22/ruby-2-4-1-released/ :)

**Comment by Drenmi** [comment]
@tgxworld: Waaah! 😅 One day ago.

**Comment by Drenmi** [comment]
Why don't they write release notes, though? :-/

**Pull request merged**
